export interface GlossaryEntry {
  id: string;
  name: string;
  formula: string;
  interpretation: string;
  availability: string;
}

export const glossaryEntries: GlossaryEntry[] = [
  {
    id: "fg",
    name: "FG%",
    formula: "Field goals made / field goal attempts",
    interpretation: "Basic shooting accuracy across all field goal attempts.",
    availability: "Shown when makes and attempts are available.",
  },
  {
    id: "two-point",
    name: "2P%",
    formula: "Two-point makes / two-point attempts",
    interpretation: "Accuracy inside the arc, separated from three-point shooting.",
    availability: "Shown when the box score exposes two-point attempts or enough data to derive them.",
  },
  {
    id: "three-point",
    name: "3P%",
    formula: "Three-point makes / three-point attempts",
    interpretation: "Accuracy on three-point shots.",
    availability: "Shown when three-point makes and attempts are available.",
  },
  {
    id: "ft",
    name: "FT%",
    formula: "Free throws made / free throw attempts",
    interpretation: "Accuracy at the free throw line.",
    availability: "Shown when free throw attempts are greater than zero.",
  },
  {
    id: "efg",
    name: "eFG%",
    formula: "(FGM + 0.5 * 3PM) / FGA",
    interpretation: "Shooting efficiency that gives extra credit for made threes.",
    availability: "Shown when field goal attempts are available.",
  },
  {
    id: "tsa",
    name: "TSA",
    formula: "FGA + 0.44 * FTA",
    interpretation: "Estimated shooting possessions used by field goal and free throw attempts.",
    availability: "Shown when field goal attempts and free throw attempts are available.",
  },
  {
    id: "ts",
    name: "TS%",
    formula: "PTS / (2 * TSA)",
    interpretation: "Scoring efficiency that accounts for twos, threes, and free throws.",
    availability: "Shown when points and shooting attempts are available.",
  },
  {
    id: "tov",
    name: "TOV%",
    formula: "TOV / (FGA + 0.44 * FTA + TOV)",
    interpretation: "Share of scoring possessions that ended in a turnover.",
    availability: "Shown when shot attempts, free throw attempts, and turnovers are available.",
  },
  {
    id: "ast",
    name: "AST%",
    formula: "AST / (mShare × Tm FGM − FGM)  (mShare = MP / (Tm MP / 5))",
    interpretation: "Fraction of teammate made field goals the player assisted on while on the floor.",
    availability: "Shown when team/player field goal makes and minutes are available.",
  },
  {
    id: "blk",
    name: "BLK%",
    formula: "BLK / (mShare × Opp 2PA)  (Opp 2PA = Opp FGA − Opp 3PA; mShare = MP / (Tm MP / 5))",
    interpretation: "Estimated share of opponent two-point attempts blocked while on the floor.",
    availability: "Shown when opponent field goal attempts and minutes are available.",
  },
  {
    id: "stl",
    name: "STL%",
    formula: "STL / (mShare × Opp possessions)  (possessions = FGA + 0.44 × FTA − ORB + TOV; mShare = MP / (Tm MP / 5))",
    interpretation: "Estimated share of opponent possessions ending in a steal while on the floor.",
    availability: "Shown when opponent possession components and minutes are available.",
  },
  {
    id: "trb",
    name: "TRB%",
    formula: "TRB / (mShare × (Tm TRB + Opp TRB))  (mShare = MP / (Tm MP / 5))",
    interpretation: "Estimated share of available rebounds the player grabbed while on the floor.",
    availability: "Shown when team/opponent total rebounds and minutes are available.",
  },
  {
    id: "usg",
    name: "USG%",
    formula: "(FGA + 0.44 × FTA + TOV) / (mShare × (Tm FGA + 0.44 × Tm FTA + Tm TOV))  (mShare = MP / (Tm MP / 5))",
    interpretation: "Estimated share of team possessions the player used while on the floor.",
    availability: "Shown when player/team shooting attempts, turnovers, and minutes are available.",
  },
  {
    id: "game-score",
    name: "Game Score",
    formula: "Dean Oliver box-score summary using points, shots, rebounds, assists, steals, blocks, fouls, and turnovers",
    interpretation: "A quick single-game estimate of player box-score impact.",
    availability: "Shown when player box score rows include the required counting stats.",
  },
  {
    id: "possessions",
    name: "Estimated Possessions",
    formula: "FGA - ORB + TOV + 0.44 * FTA",
    interpretation: "Approximate number of offensive possessions in a game.",
    availability: "Shown when team shooting, offensive rebound, turnover, and free throw data exists.",
  },
  {
    id: "ortg",
    name: "ORtg",
    formula: "100 * points / possessions",
    interpretation: "Points scored per 100 estimated possessions.",
    availability: "Shown for finished games with reliable possession estimates.",
  },
  {
    id: "drtg",
    name: "DRtg",
    formula: "100 * opponent points / possessions",
    interpretation: "Points allowed per 100 estimated possessions.",
    availability: "Shown for finished games with reliable possession estimates.",
  },
  {
    id: "pace",
    name: "Pace",
    formula: "Estimated possessions for the team game",
    interpretation: "How many possessions the game created for comparison across matchups.",
    availability: "Shown when estimated possessions can be calculated.",
  },
  {
    id: "plus-minus",
    name: "+/-",
    formula: "Points scored by player's team − points scored by opponent while the player was on the floor",
    interpretation: "Cumulative season point differential. Positive = net positive impact on the score; used as a raw on/off signal.",
    availability: "Shown when the box score API returns plusMinus for that player.",
  },
  {
    id: "double-double",
    name: "Double-Double",
    formula: "≥ 10 in any 2 of: points, rebounds, assists, steals, blocks",
    interpretation: "Count of games where the player reached double digits in two statistical categories.",
    availability: "Shown when per-game box score data is available.",
  },
  {
    id: "triple-double",
    name: "Triple-Double",
    formula: "≥ 10 in any 3 of: points, rebounds, assists, steals, blocks",
    interpretation: "Count of games where the player reached double digits in three statistical categories.",
    availability: "Shown when per-game box score data is available.",
  },
  {
    id: "quadruple-double",
    name: "Quadruple-Double",
    formula: "≥ 10 in any 4 of: points, rebounds, assists, steals, blocks",
    interpretation: "Count of games where the player reached double digits in four statistical categories.",
    availability: "Shown when per-game box score data is available.",
  },
  {
    id: "5x5",
    name: "5-by-5",
    formula: "≥ 5 in all 5 of: points, rebounds, assists, steals, blocks",
    interpretation: "Count of games where the player recorded at least 5 in every major category. Independent of double-double thresholds.",
    availability: "Shown when per-game box score data is available.",
  },
  {
    id: "pyth-wins",
    name: "Pythagorean W-L",
    formula: "G × PF^16.5 / (PF^16.5 + PA^16.5) ; L = G − W",
    interpretation: "Expected wins based on scoring efficiency. Values above actual W-L suggest the team is performing better than its record; values below suggest it has been lucky.",
    availability: "Shown when season points for and against are available.",
  },
  {
    id: "matchup-spread",
    name: "Spread",
    formula: "expPts(home) − expPts(away), where expPts = ((ORtg + opp DRtg) / 2 × strength) / 100 × avg pace, plus a flat home-court bonus",
    interpretation: "Expected winning margin, shown betting-style from your perspective (e.g. \"You -3.5\"). A symmetric efficiency blend, not a league-normalized model — treat it as a directional estimate.",
    availability: "Shown for upcoming games once both teams have recent efficiency data.",
  },
  {
    id: "matchup-total",
    name: "Over/Under",
    formula: "expPts(home) + expPts(away)",
    interpretation: "Expected combined points for the game — the projected total score.",
    availability: "Shown for upcoming games once both teams have recent efficiency data.",
  },
  {
    id: "matchup-winprob",
    name: "Win Probability",
    formula: "Φ(expected margin / margin SD), Φ = standard normal CDF",
    interpretation: "Chance your team wins, derived from the predicted spread. The margin SD and home-court bonus start from basketball priors and are not yet BuzzerBeater-calibrated.",
    availability: "Shown for upcoming games once a spread can be computed.",
  },
  {
    id: "strength-modifier",
    name: "Strength Modifier",
    formula: "clamp(form × availability): form = 1 + (avg game shape − 7) × 0.01 ; availability = 1 − injured minutes share",
    interpretation: "Roster adjustment applied to a team's expected efficiency in the matchup forecast. Down-weights teams missing rotation players to injury or in poor game shape. Enthusiasm/effort is intentionally not modeled — it is already embedded in the efficiency ratings.",
    availability: "Shown via the forecast; defaults to neutral (1.0) when roster data is missing.",
  },
];
